services:
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama-models:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - telebot-network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: telebot
    ports:
      - "8080:8080"
    working_dir: /app
    command: sh bin/run.sh
    networks:
      - telebot-network

networks:
  telebot-network:
    driver: bridge
    