services:
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama-models:/root/.ollama
    ports:
      - 11434:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - telebot-network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: telebot
    ports:
      - "8080:8080"
    working_dir: /app
    command: sh bin/run.sh
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - telebot-network

networks:
  telebot-network:
    driver: bridge
    